In [1]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
#import data
Raw_mail_data  = pd.read_csv(r"C:\Users\khush\Downloads\mail_data.csv")
pd.set_option('display.max.rows',5575)
Raw_mail_data

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
5        spam  FreeMsg Hey there darling it's been 3 week's n...
6         ham  Even my brother is not like to speak with me. ...
7         ham  As per your request 'Melle Melle (Oru Minnamin...
8        spam  WINNER!! As a valued network customer you have...
9        spam  Had your mobile 11 months or more? U R entitle...
10        ham  I'm gonna be home soon and i don't want to tal...
11       spam  SIX chances to win CASH! From 100 to 20,000 po...
12       spam  URGENT! You have won a 1 week FREE membership ...
13        ham  I've been searching for the right words to tha...
14        ham                I HAVE A DATE ON SUNDAY WITH WILL!!
15       spam  XXXMobileMovieClub: To use your credit, click ...
16        ham                         Oh k...i'm watching here:)
17        ham  Eh u remember how 2 spell his name... Yes i di...
18        ham  Fine if thats the way u feel. Thats the way ...
19       spam  England v Macedonia - dont miss the goals/team...
20        ham          Is that seriously how you spell his name?
21        ham    I‘m going to try for 2 months ha ha only joking
22        ham  So ü pay first lar... Then when is da stock co...
23        ham  Aft i finish my lunch then i go str down lor. ...
24        ham  Ffffffffff. Alright no way I can meet up with ...
25        ham  Just forced myself to eat a slice. I'm really ...
26        ham                     Lol your always so convincing.
27        ham  Did you catch the bus ? Are you frying an egg ...
28        ham  I'm back &amp; we're packing the car now, I'll...
29        ham  Ahhh. Work. I vaguely remember that! What does...
30        ham  Wait that's still not all that clear, were you...
31        ham  Yeah he got in at 2 and was v apologetic. n ha...
32        ham                      K tell me anything about you.
33        ham  For fear of fainting with the of all that hous...
34       spam  Thanks for your subscription to Ringtone UK yo...
35        ham  Yup... Ok i go home look at the timings then i...
36        ham    Oops, I'll let you know when my roommate's done
37        ham                       I see the letter B on my car
38        ham                        Anything lor... U decide...
39        ham  Hello! How's you and how did saturday go? I wa...
40        ham  Pls go ahead with watts. I just wanted to be s...
41        ham  Did I forget to tell you ? I want you , I need...
42       spam  07732584351 - Rodger Burns - MSG = We tried to...
43        ham                                WHO ARE YOU SEEING?
44        ham  Great! I hope you like your man well endowed. ...
45        ham                   No calls..messages..missed calls
46        ham      Didn't you get hep b immunisation in nigeria.
47        ham                    Fair enough, anything going on?
48        ham  Yeah hopefully, if tyler can't do it I could m...
49        ham  U don't know how stubborn I am. I didn't even ...
50        ham  What you thinked about me. First time you saw ...
51        ham  A gram usually runs like  &lt;#&gt; , a half e...
52        ham  K fyi x has a ride early tomorrow morning but ...
53        ham  Wow. I never realized that you were so embaras...
54       spam  SMS. ac Sptv: The New Jersey Devils and the De...
55        ham  Do you know what Mallika Sherawat did yesterda...
56       spam  Congrats! 1 year special cinema pass for 2 is ...
57        ham                 Sorry, I'll call later in meeting.
58        ham                             Tell where you reached
59        ham           Yes..gauti and sehwag out of odi series.
60        ham  Your gonna have to pick up a $1 burger for you...
61        ham   Ha ha ha good joke. Girls are situation seekers.
62        ham                          Its a part of checking IQ
63        ham  Sorry my roommates took forever, it ok if I co...
64        ham  Ok lar i double check wif da hair dresser alre...
65       spam  As a valued customer, I am pleased to advise y...
66        ham  Today is "song dedicated day.." Which song wil...
67       spam  Urgent UR awarded a complimentary trip to Euro...
68       spam  Did you hear about the new "Divorce Barbie"? I...
69        ham                 I plane to give on this month end.
70        ham     Wah lucky man... Then can save money... Hee...
71        ham                      Finished class where are you.
72        ham      HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX
73        ham         K..k:)where are you?how did you performed?
74        ham                               U can call me now...
75        ham        I am waiting machan. Call me once you free.
76        ham  Thats cool. i am a gentleman and will treat yo...
77        ham  I like you peoples very much:) but am very shy...
78        ham         Does not operate after  &lt;#&gt;  or what
79        ham  Its not the same here. Still looking for a job...
80        ham                             Sorry, I'll call later
81        ham                    K. Did you call me just now ah?
82        ham                   Ok i am on the way to home hi hi
83        ham               You will be in the place of that man
84        ham                                     Yup next stop.
85        ham  I call you later, don't have network. If urgnt...
86        ham  For real when u getting on yo? I only need 2 m...
87        ham  Yes I started to send requests to make it but ...
88        ham         I'm really not up to it still tonight babe
89        ham          Ela kano.,il download, come wen ur free..
90        ham  Yeah do! Don‘t stand to close tho- you‘ll catc...
91        ham  Sorry to be a pain. Is it ok if we meet anothe...
92        ham  Smile in Pleasure Smile in Pain Smile when tro...
93       spam  Please call our customer service representativ...
94        ham  Havent planning to buy later. I check already ...
95       spam  Your free ringtone is waiting to be collected....
96        ham                  Watching telugu movie..wat abt u?
97        ham  i see. When we finish we have loads of loans t...
98        ham  Hi. Wk been ok - on hols now! Yes on for a bit...
99        ham                    I see a cup of coffee animation
100       ham  Please don't text me anymore. I have nothing e...
101       ham  Okay name ur price as long as its legal! Wen c...
102       ham  I'm still looking for a car to buy. And have n...
103       ham  As per your request 'Melle Melle (Oru Minnamin...
104       ham  wow. You're right! I didn't mean to do that. I...
105       ham       Umma my life and vava umma love you lot dear
106       ham  Thanks a lot for your wishes on my birthday. T...
107       ham        Aight, I'll hit you up when I get some cash
108       ham  How would my ip address test that considering ...
109       ham  I know! Grumpy old people. My mom was like you...
110       ham                     Dont worry. I guess he's busy.
111       ham           What is the plural of the noun research?
112       ham                    Going for dinner.msg you after.
113       ham  I'm ok wif it cos i like 2 try new things. But...
114      spam  GENT! We are trying to contact you. Last weeke...
115       ham  Wa, ur openin sentence very formal... Anyway, ...
116       ham  As I entered my cabin my PA said, '' Happy B'd...
117      spam  You are a winner U have been specially selecte...
118       ham  Goodo! Yes we must speak friday - egg-potato r...
119       ham  Hmm...my uncle just informed me that he's payi...
120      spam  PRIVATE! Your 2004 Account Statement for 07742...
121      spam  URGENT! Your Mobile No. was awarded £2000 Bonu...
122       ham  here is my new address -apples&pairs&all that ...
123      spam  Todays Voda numbers ending 7548 are selected t...
124       ham  I am going to sao mu today. Will be done only ...
125       ham             Ü predict wat time ü'll finish buying?
126       ham                               Good stuff, will do.
127       ham  Just so that you know,yetunde hasn't sent mone...
128       ham                             Are you there in room.
129       ham  HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R B...
130       ham                       K..k:)how much does it cost?
131       ham                                          I'm home.
132       ham            Dear, will call Tmorrow.pls accomodate.
133       ham                          First answer my question.
134      spam  Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
135      spam  Want 2 get laid tonight? Want real Dogging loc...
136       ham             I only haf msn. It's yijue@hotmail.com
137       ham                 He is there. You call and meet him
138       ham     No no. I will check all rooms befor activities
139      spam  You'll not rcv any more msgs from the chat svc...
140       ham  Got c... I lazy to type... I forgot ü in lect....
141       ham                  K, text me when you're on the way
142       ham                        Sir, Waiting for your mail.
143       ham  A swt thought: "Nver get tired of doing little...
144       ham         I know you are. Can you pls open the back?
145       ham                          Yes see ya not on the dot
146       ham   Whats the staff name who is taking class for us?
147      spam  FreeMsg Why haven't you replied to my text? I'...
148       ham  Ummma.will call after check in.our life will b...
149       ham                  K..i deleted my contact that why?
150       ham                     Sindu got job in birla soft ..
151       ham      The wine is flowing and i'm i have nevering..
152       ham  Yup i thk cine is better cos no need 2 go down...
153       ham                          Ok... Ur typical reply...
154       ham  As per your request 'Melle Melle (Oru Minnamin...
155       ham  You are everywhere dirt, on the floor, the win...
156       ham                       Aaooooright are you at work?
157       ham                        I'm leaving my house now...
158       ham  Hello, my love. What are you doing? Did you ge...
159      spam  Customer service annoncement. You have a New Y...
160      spam  You are a winner U have been specially selecte...
161       ham  Keep yourself safe for me because I need you a...
162       ham  New car and house for my parents.:)i have only...
163       ham  I'm so in love with you. I'm excited each day ...
164      spam  -PLS STOP bootydelious (32/F) is inviting you ...
165      spam  BangBabes Ur order is on the way. U SHOULD rec...
166       ham  I place all ur points on e cultures module alr...
167      spam  URGENT! We are trying to contact you. Last wee...
168       ham  Hi frnd, which is best way to avoid missunders...
169       ham  Great escape. I fancy the bridge but needs her...
170       ham  Yes :)it completely in out of form:)clark also...
171       ham  Sir, I need AXIS BANK account no and bank addr...
172       ham  Hmmm.. Thk sure got time to hop ard... Ya, can...
173       ham                   What time you coming down later?
174       ham  Bloody hell, cant believe you forgot my surnam...
175       ham  Well, i'm gonna finish my bath now. Have a goo...
176       ham  Let me know when you've got the money so carlo...
177       ham                         U still going to the mall?
178       ham  Turns out my friends are staying for the whole...
179       ham  Text her. If she doesnt reply let me know so i...
180       ham  Hi! You just spoke to MANEESHA V. We'd like to...
181       ham  You lifted my hopes with the offer of money. I...
182       ham                            Lol no. U can trust me.
183       ham  ok. I am a gentleman and will treat you with d...
184       ham                           He will, you guys close?
185       ham                         Going on nothing great.bye
186       ham  Hello handsome ! Are you finding that job ? No...
187       ham                 Haha awesome, be there in a minute
188      spam  Please call our customer service representativ...
189       ham  Have you got Xmas radio times. If not i will g...
190       ham  I jus reached home. I go bathe first. But my s...
191      spam  Are you unique enough? Find out from 30th Augu...
192       ham  I'm sorry. I've joined the league of people th...
193       ham              Hi :)finally i completed the course:)
194       ham  It will stop on itself. I however suggest she ...
195       ham  How are you doing? Hope you've settled in for ...
196       ham                       Gud mrng dear hav a nice day
197       ham                       Did u got that persons story
198       ham  is your hamster dead? Hey so tmr i meet you at...
199       ham  Hi its Kate how is your evening? I hope i can ...
200       ham           Found it, ENC  &lt;#&gt; , where you at?
201       ham                       I sent you  &lt;#&gt;  bucks
202       ham  Hello darlin ive finished college now so txt m...
203       ham  Your account has been refilled successfully by...
204       ham                           Goodmorning sleeping ga.
205       ham                          U call me alter at 11 ok.
206       ham  Ü say until like dat i dun buy ericsson oso ca...
207       ham  As I entered my cabin my PA said, '' Happy B'd...
208       ham                       Aight yo, dats straight dogg
209       ham  You please give us connection today itself bef...
210       ham            Both :) i shoot big loads so get ready!
211       ham  What's up bruv, hope you had a great break. Do...
212       ham                         Home so we can always chat
213       ham                            K:)k:)good:)study well.
214       ham                            Yup... How ü noe leh...
215       ham                    Sounds great! Are you home now?
216       ham  Finally the match heading towards draw as your...
217       ham   Tired. I haven't slept well the past few nights.
218       ham          Easy ah?sen got selected means its good..
219       ham                   I have to take exam with march 3
220       ham  Yeah you should. I think you can use your gt a...
221       ham                          Ok no prob. Take ur time.
222       ham  There is os called ubandu which will run witho...
223       ham                             Sorry, I'll call later
224       ham  U say leh... Of course nothing happen lar. Not...
225      spam  500 New Mobiles from 2004, MUST GO! Txt: NOKIA...
226       ham  Would really appreciate if you call me. Just n...
227      spam  Will u meet ur dream partner soon? Is ur caree...
228       ham                     Hey company elama po mudyadhu.
229       ham  Life is more strict than teacher... Bcoz Teach...
230       ham                 Dear good morning now only i am up
231       ham  Get down in gandhipuram and walk to cross cut ...
232       ham              Dear we are going to our rubber place
233       ham                  Sorry battery died, yeah I'm here
234       ham   Yes:)here tv is always available in work place..
235      spam  Text & meet someone sexy today. U can find a d...
236       ham  I have printed it oh. So  &lt;#&gt;  come upst...
237       ham  Or ill be a little closer like at the bus stop...
238       ham             Where are you?when wil you reach here?
239       ham  New Theory: Argument wins d SITUATION, but los...
240      spam  U 447801259231 have a secret admirer who is lo...
241       ham  Tomarrow final hearing on my laptop case so i ...
242       ham      PLEASSSSSSSEEEEEE TEL ME V AVENT DONE SPORTSx
243       ham  Okay. No no, just shining on. That was meant t...
244       ham  Although i told u dat i'm into baig face watch...
245       ham              U don't remember that old commercial?
246       ham  Too late. I said i have the website. I didn't ...
247       ham                     I asked you to call him now ok
248       ham                    Kallis wont bat in 2nd innings.
249       ham  It didnt work again oh. Ok goodnight then. I.l...
250      spam  Congratulations ur awarded 500 of CD vouchers ...
251       ham       Ranjith cal drpd Deeraj and deepak 5min hold
252       ham  Wen ur lovable bcums angry wid u, dnt take it ...
253       ham                        What you doing?how are you?
254       ham  Ups which is 3days also, and the shipping comp...
255       ham             I'm back, lemme know when you're ready
256       ham  Don't necessarily expect it to be done before ...
257       ham        Mmm so yummy babe ... Nice jolt to the suzy
258       ham               Where are you lover ? I need you ...
259      spam  We tried to contact you re your reply to our o...
260       ham  I‘m parked next to a MINI!!!! When are you com...
261       ham                                                Yup
262       ham  Anyway i'm going shopping on my own now. Cos m...
263       ham  MY NO. IN LUTON 0125698789 RING ME IF UR AROUN...
264      spam  Hey I am really horny want to chat or see me n...
265       ham                         Why you Dint come with us.
266       ham                Same. Wana plan a trip sometme then
267       ham    Not sure yet, still trying to get a hold of him
268      spam  Ur ringtone service has changed! 25 Free credi...
269       ham    The evo. I just had to download flash. Jealous?
270      spam  Ringtone Club: Get the UK singles chart on you...
271       ham  Come to mu, we're sorting out our narcotics si...
272       ham  Night has ended for another day, morning has c...
273      spam  HMV BONUS SPECIAL 500 pounds of genuine HMV vo...
274       ham              Usf I guess, might as well take 1 car
275       ham                    No objection. My bf not coming.
276       ham                                           Thanx...
277       ham             Tell rob to mack his gf in the theater
278       ham                     Awesome, I'll see you in a bit
279       ham    Just sent it. So what type of food do you like?
280       ham  All done? All handed in? Celebrations in full ...
281       ham                             You got called a tool?
282       ham  Wen u miss someone, the person is definitely s...
283       ham                      Ok. I asked for money how far
284       ham                                            Okie...
285       ham  Yeah I think my usual guy's still passed out f...
286       ham  K, I might come by tonight then if my class le...
287       ham                                               Ok..
288       ham  hi baby im cruisin with my girl friend what r ...
289       ham  My life Means a lot to me, Not because I love ...
290       ham  Dear,shall mail tonite.busy in the street,shal...
291       ham              Hey you told your name to gautham ah?
292       ham  Haf u found him? I feel so stupid da v cam was...
293       ham                              Oops. 4 got that bit.
294       ham                             Are you this much buzy
295       ham  I accidentally deleted the message. Resend ple...
296      spam  T-Mobile customer you may now claim your FREE ...
297       ham  Unless it's a situation where YOU GO GURL woul...
298       ham  Hurt me... Tease me... Make me cry... But in t...
299       ham  I cant pick the phone right now. Pls send a me...
300       ham  Need a coffee run tomo?Can't believe it's that...
301       ham  Awesome, I remember the last time we got someb...
302       ham  Shit that is really shocking and scary, cant i...
303       ham  Oh and by the way you do have more food in you...
304       ham                           He is a womdarfull actor
305      spam  SMS. ac Blind Date 4U!: Rodds1 is 21/m from Ab...

In [3]:
#data information
Raw_mail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [4]:
#replace null values with ' ' space
mail_data = Raw_mail_data.where((pd.notnull(Raw_mail_data)),' ')

In [5]:
#view top 5 values of data 
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
#label spam mail as 0 and non spam mail as 1

mail_data.loc[mail_data['Category'] == 'spam', 'Category'] = 0
mail_data.loc[mail_data['Category'] == 'ham', 'Category'] = 1

In [7]:
#separate the data as text and labels 
X = mail_data['Message']
Y = mail_data['Category']

In [8]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
5       FreeMsg Hey there darling it's been 3 week's n...
6       Even my brother is not like to speak with me. ...
7       As per your request 'Melle Melle (Oru Minnamin...
8       WINNER!! As a valued network customer you have...
9       Had your mobile 11 months or more? U R entitle...
10      I'm gonna be home soon and i don't want to tal...
11      SIX chances to win CASH! From 100 to 20,000 po...
12      URGENT! You have won a 1 week FREE membership ...
13      I've been searching for the right words to tha...
14                    I HAVE A DATE ON SUNDAY WITH WILL!!
15      XXXMobileMovieClub: To use your credit, click ...
16                             Oh k...i'm watching here:)
17      Eh u remember how 2 spell his name... Yes i di...
18      Fine if thats the way u feel. Thats the way ...
19      England v Macedonia - dont miss the goals/team...
20              Is that seriously how you spell his name?
21        I‘m going to try for 2 months ha ha only joking
22      So ü pay first lar... Then when is da stock co...
23      Aft i finish my lunch then i go str down lor. ...
24      Ffffffffff. Alright no way I can meet up with ...
25      Just forced myself to eat a slice. I'm really ...
26                         Lol your always so convincing.
27      Did you catch the bus ? Are you frying an egg ...
28      I'm back &amp; we're packing the car now, I'll...
29      Ahhh. Work. I vaguely remember that! What does...
30      Wait that's still not all that clear, were you...
31      Yeah he got in at 2 and was v apologetic. n ha...
32                          K tell me anything about you.
33      For fear of fainting with the of all that hous...
34      Thanks for your subscription to Ringtone UK yo...
35      Yup... Ok i go home look at the timings then i...
36        Oops, I'll let you know when my roommate's done
37                           I see the letter B on my car
38                            Anything lor... U decide...
39      Hello! How's you and how did saturday go? I wa...
40      Pls go ahead with watts. I just wanted to be s...
41      Did I forget to tell you ? I want you , I need...
42      07732584351 - Rodger Burns - MSG = We tried to...
43                                    WHO ARE YOU SEEING?
44      Great! I hope you like your man well endowed. ...
45                       No calls..messages..missed calls
46          Didn't you get hep b immunisation in nigeria.
47                        Fair enough, anything going on?
48      Yeah hopefully, if tyler can't do it I could m...
49      U don't know how stubborn I am. I didn't even ...
50      What you thinked about me. First time you saw ...
51      A gram usually runs like  &lt;#&gt; , a half e...
52      K fyi x has a ride early tomorrow morning but ...
53      Wow. I never realized that you were so embaras...
54      SMS. ac Sptv: The New Jersey Devils and the De...
55      Do you know what Mallika Sherawat did yesterda...
56      Congrats! 1 year special cinema pass for 2 is ...
57                     Sorry, I'll call later in meeting.
58                                 Tell where you reached
59               Yes..gauti and sehwag out of odi series.
60      Your gonna have to pick up a $1 burger for you...
61       Ha ha ha good joke. Girls are situation seekers.
62                              Its a part of checking IQ
63      Sorry my roommates took forever, it ok if I co...
64      Ok lar i double check wif da hair dresser alre...
65      As a valued customer, I am pleased to advise y...
66      Today is "song dedicated day.." Which song wil...
67      Urgent UR awarded a complimentary trip to Euro...
68      Did you hear about the new "Divorce Barbie"? I...
69                     I plane to give on this month end.
70         Wah lucky man... Then can save money... Hee...
71                          Finished class where are you.
72          HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX
73             K..k:)where are you?how did you performed?
74                                   U can call me now...
75            I am waiting machan. Call me once you free.
76      Thats cool. i am a gentleman and will treat yo...
77      I like you peoples very much:) but am very shy...
78             Does not operate after  &lt;#&gt;  or what
79      Its not the same here. Still looking for a job...
80                                 Sorry, I'll call later
81                        K. Did you call me just now ah?
82                       Ok i am on the way to home hi hi
83                   You will be in the place of that man
84                                         Yup next stop.
85      I call you later, don't have network. If urgnt...
86      For real when u getting on yo? I only need 2 m...
87      Yes I started to send requests to make it but ...
88             I'm really not up to it still tonight babe
89              Ela kano.,il download, come wen ur free..
90      Yeah do! Don‘t stand to close tho- you‘ll catc...
91      Sorry to be a pain. Is it ok if we meet anothe...
92      Smile in Pleasure Smile in Pain Smile when tro...
93      Please call our customer service representativ...
94      Havent planning to buy later. I check already ...
95      Your free ringtone is waiting to be collected....
96                      Watching telugu movie..wat abt u?
97      i see. When we finish we have loads of loans t...
98      Hi. Wk been ok - on hols now! Yes on for a bit...
99                        I see a cup of coffee animation
100     Please don't text me anymore. I have nothing e...
101     Okay name ur price as long as its legal! Wen c...
102     I'm still looking for a car to buy. And have n...
103     As per your request 'Melle Melle (Oru Minnamin...
104     wow. You're right! I didn't mean to do that. I...
105          Umma my life and vava umma love you lot dear
106     Thanks a lot for your wishes on my birthday. T...
107           Aight, I'll hit you up when I get some cash
108     How would my ip address test that considering ...
109     I know! Grumpy old people. My mom was like you...
110                        Dont worry. I guess he's busy.
111              What is the plural of the noun research?
112                       Going for dinner.msg you after.
113     I'm ok wif it cos i like 2 try new things. But...
114     GENT! We are trying to contact you. Last weeke...
115     Wa, ur openin sentence very formal... Anyway, ...
116     As I entered my cabin my PA said, '' Happy B'd...
117     You are a winner U have been specially selecte...
118     Goodo! Yes we must speak friday - egg-potato r...
119     Hmm...my uncle just informed me that he's payi...
120     PRIVATE! Your 2004 Account Statement for 07742...
121     URGENT! Your Mobile No. was awarded £2000 Bonu...
122     here is my new address -apples&pairs&all that ...
123     Todays Voda numbers ending 7548 are selected t...
124     I am going to sao mu today. Will be done only ...
125                Ü predict wat time ü'll finish buying?
126                                  Good stuff, will do.
127     Just so that you know,yetunde hasn't sent mone...
128                                Are you there in room.
129     HEY GIRL. HOW R U? HOPE U R WELL ME AN DEL R B...
130                          K..k:)how much does it cost?
131                                             I'm home.
132               Dear, will call Tmorrow.pls accomodate.
133                             First answer my question.
134     Sunshine Quiz Wkly Q! Win a top Sony DVD playe...
135     Want 2 get laid tonight? Want real Dogging loc...
136                I only haf msn. It's yijue@hotmail.com
137                    He is there. You call and meet him
138        No no. I will check all rooms befor activities
139     You'll not rcv any more msgs from the chat svc...
140     Got c... I lazy to type... I forgot ü in lect....
141                     K, text me when you're on the way
142                           Sir, Waiting for your mail.
143     A swt thought: "Nver get tired of doing little...
144            I know you are. Can you pls open the back?
145                             Yes see ya not on the dot
146      Whats the staff name who is taking class for us?
147     FreeMsg Why haven't you replied to my text? I'...
148     Ummma.will call after check in.our life will b...
149                     K..i deleted my contact that why?
150                        Sindu got job in birla soft ..
151         The wine is flowing and i'm i have nevering..
152     Yup i thk cine is better cos no need 2 go down...
153                             Ok... Ur typical reply...
154     As per your request 'Melle Melle (Oru Minnamin...
155     You are everywhere dirt, on the floor, the win...
156                          Aaooooright are you at work?
157                           I'm leaving my house now...
158     Hello, my love. What are you doing? Did you ge...
159     Customer service annoncement. You have a New Y...
160     You are a winner U have been specially selecte...
161     Keep yourself safe for me because I need you a...
162     New car and house for my parents.:)i have only...
163     I'm so in love with you. I'm excited each day ...
164     -PLS STOP bootydelious (32/F) is inviting you ...
165     BangBabes Ur order is on the way. U SHOULD rec...
166     I place all ur points on e cultures module alr...
167     URGENT! We are trying to contact you. Last wee...
168     Hi frnd, which is best way to avoid missunders...
169     Great escape. I fancy the bridge but needs her...
170     Yes :)it completely in out of form:)clark also...
171     Sir, I need AXIS BANK account no and bank addr...
172     Hmmm.. Thk sure got time to hop ard... Ya, can...
173                      What time you coming down later?
174     Bloody hell, cant believe you forgot my surnam...
175     Well, i'm gonna finish my bath now. Have a goo...
176     Let me know when you've got the money so carlo...
177                            U still going to the mall?
178     Turns out my friends are staying for the whole...
179     Text her. If she doesnt reply let me know so i...
180     Hi! You just spoke to MANEESHA V. We'd like to...
181     You lifted my hopes with the offer of money. I...
182                               Lol no. U can trust me.
183     ok. I am a gentleman and will treat you with d...
184                              He will, you guys close?
185                            Going on nothing great.bye
186     Hello handsome ! Are you finding that job ? No...
187                    Haha awesome, be there in a minute
188     Please call our customer service representativ...
189     Have you got Xmas radio times. If not i will g...
190     I jus reached home. I go bathe first. But my s...
191     Are you unique enough? Find out from 30th Augu...
192     I'm sorry. I've joined the league of people th...
193                 Hi :)finally i completed the course:)
194     It will stop on itself. I however suggest she ...
195     How are you doing? Hope you've settled in for ...
196                          Gud mrng dear hav a nice day
197                          Did u got that persons story
198     is your hamster dead? Hey so tmr i meet you at...
199     Hi its Kate how is your evening? I hope i can ...
200              Found it, ENC  &lt;#&gt; , where you at?
201                          I sent you  &lt;#&gt;  bucks
202     Hello darlin ive finished college now so txt m...
203     Your account has been refilled successfully by...
204                              Goodmorning sleeping ga.
205                             U call me alter at 11 ok.
206     Ü say until like dat i dun buy ericsson oso ca...
207     As I entered my cabin my PA said, '' Happy B'd...
208                          Aight yo, dats straight dogg
209     You please give us connection today itself bef...
210               Both :) i shoot big loads so get ready!
211     What's up bruv, hope you had a great break. Do...
212                            Home so we can always chat
213                               K:)k:)good:)study well.
214                               Yup... How ü noe leh...
215                       Sounds great! Are you home now?
216     Finally the match heading towards draw as your...
217      Tired. I haven't slept well the past few nights.
218             Easy ah?sen got selected means its good..
219                      I have to take exam with march 3
220     Yeah you should. I think you can use your gt a...
221                             Ok no prob. Take ur time.
222     There is os called ubandu which will run witho...
223                                Sorry, I'll call later
224     U say leh... Of course nothing happen lar. Not...
225     500 New Mobiles from 2004, MUST GO! Txt: NOKIA...
226     Would really appreciate if you call me. Just n...
227     Will u meet ur dream partner soon? Is ur caree...
228                        Hey company elama po mudyadhu.
229     Life is more strict than teacher... Bcoz Teach...
230                    Dear good morning now only i am up
231     Get down in gandhipuram and walk to cross cut ...
232                 Dear we are going to our rubber place
233                     Sorry battery died, yeah I'm here
234      Yes:)here tv is always available in work place..
235     Text & meet someone sexy today. U can find a d...
236     I have printed it oh. So  &lt;#&gt;  come upst...
237     Or ill be a little closer like at the bus stop...
238                Where are you?when wil you reach here?
239     New Theory: Argument wins d SITUATION, but los...
240     U 447801259231 have a secret admirer who is lo...
241     Tomarrow final hearing on my laptop case so i ...
242         PLEASSSSSSSEEEEEE TEL ME V AVENT DONE SPORTSx
243     Okay. No no, just shining on. That was meant t...
244     Although i told u dat i'm into baig face watch...
245                 U don't remember that old commercial?
246     Too late. I said i have the website. I didn't ...
247                        I asked you to call him now ok
248                       Kallis wont bat in 2nd innings.
249     It didnt work again oh. Ok goodnight then. I.l...
250     Congratulations ur awarded 500 of CD vouchers ...
251          Ranjith cal drpd Deeraj and deepak 5min hold
252     Wen ur lovable bcums angry wid u, dnt take it ...
253                           What you doing?how are you?
254     Ups which is 3days also, and the shipping comp...
255                I'm back, lemme know when you're ready
256     Don't necessarily expect it to be done before ...
257           Mmm so yummy babe ... Nice jolt to the suzy
258                  Where are you lover ? I need you ...
259     We tried to contact you re your reply to our o...
260     I‘m parked next to a MINI!!!! When are you com...
261                                                   Yup
262     Anyway i'm going shopping on my own now. Cos m...
263     MY NO. IN LUTON 0125698789 RING ME IF UR AROUN...
264     Hey I am really horny want to chat or see me n...
265                            Why you Dint come with us.
266                   Same. Wana plan a trip sometme then
267       Not sure yet, still trying to get a hold of him
268     Ur ringtone service has changed! 25 Free credi...
269       The evo. I just had to download flash. Jealous?
270     Ringtone Club: Get the UK singles chart on you...
271     Come to mu, we're sorting out our narcotics si...
272     Night has ended for another day, morning has c...
273     HMV BONUS SPECIAL 500 pounds of genuine HMV vo...
274                 Usf I guess, might as well take 1 car
275                       No objection. My bf not coming.
276                                              Thanx...
277                Tell rob to mack his gf in the theater
278                        Awesome, I'll see you in a bit
279       Just sent it. So what type of food do you like?
280     All done? All handed in? Celebrations in full ...
281                                You got called a tool?
282     Wen u miss someone, the person is definitely s...
283                         Ok. I asked for money how far
284                                               Okie...
285     Yeah I think my usual guy's still passed out f...
286     K, I might come by tonight then if my class le...
287                                                  Ok..
288     hi baby im cruisin with my girl friend what r ...
289     My life Means a lot to me, Not because I love ...
290     Dear,shall mail tonite.busy in the street,shal...
291                 Hey you told your name to gautham ah?
292     Haf u found him? I feel so stupid da v cam was...
293                                 Oops. 4 got that bit.
294                                Are you this much buzy
295     I accidentally deleted the message. Resend ple...
296     T-Mobile customer you may now claim your FREE ...
297     Unless it's a situation where YOU GO GURL woul...
298     Hurt me... Tease me... Make me cry... But in t...
299     I cant pick the phone right now. Pls send a me...
300     Need a coffee run tomo?Can't believe it's that...
301     Awesome, I remember the last time we got someb...
302     Shit that is really shocking and scary, cant i...
303     Oh and by the way you do have more food in you...
304                              He is a womdarfull actor
305     SMS. ac Blind Date 4U!: Rodds1 is 21/m from Ab...
306     Yup... From what i remb... I think should be c...
307                            Jos ask if u wana meet up?
308     Lol yes. Our friendship is hanging on a thread...
309     TheMob> Check out our newest selection of cont...
310     Where are the garage keys? They aren't on the ...
311     Today is ACCEPT DAY..U Accept me as? Brother S...
312     Think ur smart ? Win £200 this week in our wee...
313     He says he'll give me a call when his friend's...
314     Hi the way I was with u 2day, is the normal wa...
315             You made my day. Do have a great day too.
316                            K.k:)advance happy pongal.
317     Hmmm... Guess we can go 4 kb n power yoga... H...
318        Not really dude, have no friends i'm afraid :(
319     December only! Had your mobile 11mths+? You ar...
320                               Coffee cake, i guess...
321     Merry Christmas to you too babe, i love ya *ki...
322     Hey... Why dont we just go watch x men and hav...
323     cud u tell ppl im gona b a bit l8 cos 2 buses ...
324     That would be great. We'll be at the Guild. Co...
325                        No problem. How are you doing?
326                      No calls..messages..missed calls
327                       Hi da:)how is the todays class?
328     I'd say that's a good sign but, well, you know...
329                      Cool, text me when you're parked
330     I'm reading the text i just sent you. Its mean...
331                                K.k:)apo k.good movie.
332     Maybe i could get book out tomo then return it...
333     Call Germany for only 1 pence per minute! Call...
334     Any chance you might have had with me evaporat...
335     Valentines Day Special! Win over £1000 in our ...
336         Ta-Daaaaa! I am home babe, are you still up ?
337     Cool. So how come you havent been wined and di...
338                            Just sleeping..and surfing
339                                Sorry, I'll call later
340             U calling me right? Call my hand phone...
341                          Ok that's great thanx a lot.
342     I take it the post has come then! You must hav...
343                         Where u been hiding stranger?

In [9]:
print(Y)

0       1
1       1
2       0
3       1
4       1
5       0
6       1
7       1
8       0
9       0
10      1
11      0
12      0
13      1
14      1
15      0
16      1
17      1
18      1
19      0
20      1
21      1
22      1
23      1
24      1
25      1
26      1
27      1
28      1
29      1
30      1
31      1
32      1
33      1
34      0
35      1
36      1
37      1
38      1
39      1
40      1
41      1
42      0
43      1
44      1
45      1
46      1
47      1
48      1
49      1
50      1
51      1
52      1
53      1
54      0
55      1
56      0
57      1
58      1
59      1
60      1
61      1
62      1
63      1
64      1
65      0
66      1
67      0
68      0
69      1
70      1
71      1
72      1
73      1
74      1
75      1
76      1
77      1
78      1
79      1
80      1
81      1
82      1
83      1
84      1
85      1
86      1
87      1
88      1
89      1
90      1
91      1
92      1
93      0
94      1
95      0
96      1
97      1
98      1
99      1
100     1
101     1
102     1
103     1
104     1
105     1
106     1
107     1
108     1
109     1
110     1
111     1
112     1
113     1
114     0
115     1
116     1
117     0
118     1
119     1
120     0
121     0
122     1
123     0
124     1
125     1
126     1
127     1
128     1
129     1
130     1
131     1
132     1
133     1
134     0
135     0
136     1
137     1
138     1
139     0
140     1
141     1
142     1
143     1
144     1
145     1
146     1
147     0
148     1
149     1
150     1
151     1
152     1
153     1
154     1
155     1
156     1
157     1
158     1
159     0
160     0
161     1
162     1
163     1
164     0
165     0
166     1
167     0
168     1
169     1
170     1
171     1
172     1
173     1
174     1
175     1
176     1
177     1
178     1
179     1
180     1
181     1
182     1
183     1
184     1
185     1
186     1
187     1
188     0
189     1
190     1
191     0
192     1
193     1
194     1
195     1
196     1
197     1
198     1
199     1
200     1
201     1
202     1
203     1
204     1
205     1
206     1
207     1
208     1
209     1
210     1
211     1
212     1
213     1
214     1
215     1
216     1
217     1
218     1
219     1
220     1
221     1
222     1
223     1
224     1
225     0
226     1
227     0
228     1
229     1
230     1
231     1
232     1
233     1
234     1
235     0
236     1
237     1
238     1
239     1
240     0
241     1
242     1
243     1
244     1
245     1
246     1
247     1
248     1
249     1
250     0
251     1
252     1
253     1
254     1
255     1
256     1
257     1
258     1
259     0
260     1
261     1
262     1
263     1
264     0
265     1
266     1
267     1
268     0
269     1
270     0
271     1
272     1
273     0
274     1
275     1
276     1
277     1
278     1
279     1
280     1
281     1
282     1
283     1
284     1
285     1
286     1
287     1
288     1
289     1
290     1
291     1
292     1
293     1
294     1
295     1
296     0
297     1
298     1
299     1
300     1
301     1
302     1
303     1
304     1
305     0
306     1
307     1
308     1
309     0
310     1
311     1
312     0
313     1
314     1
315     1
316     1
317     1
318     1
319     0
320     1
321     1
322     1
323     1
324     1
325     1
326     1
327     1
328     1
329     1
330     1
331     1
332     1
333     0
334     1
335     0
336     1
337     1
338     1
339     1
340     1
341     1
342     1
343     1
344     1
345     1
346     1
347     1
348     1
349     0
350     1
351     1
352     1
353     1
354     1
355     1
356     1
357     0
358     0
359     1
360     1
361     1
362     1
363     1
364     1
365     1
366     1
367     0
368     0
369     1
370     1
371     1
372     1
373     1
374     1
375     0
376     1
377     1
378     1
379     1
380     1
381     1
382     1
383     1
384     1
385     0
386     1
387     1
388     1
389     0
390     1
391     1
392     1
393     1
394     1
395     1
396     1
397     1
398     1
399     1
400     1
401     0
402     1
403     1
404     1
405     1
406     1
407     1
408     1
409     1
410     1
411     1
412     1
413     1
414     1
415     0
416     1
417     1
418     0
419     1
420     0
421     1
422     0
423     1
424     0
425     1
426     1
427     1
428     1
429     1
430     1
431     1
432     1
433     0
434     1
435     1
436     1
437     1
438     1
439     1
440     1
441     1
442     1
443     1
444     1
445     1
446     1
447     1
448     1
449     1
450     1
451     1
452     1
453     1
454     1
455     0
456     1
457     1
458     1
459     1
460     1
461     1
462     1
463     0
464     1
465     1
466     1
467     1
468     1
469     1
470     1
471     0
472     1
473     1
474     0
475     1
476     1
477     1
478     1
479     1
480     1
481     1
482     1
483     1
484     1
485     1
486     1
487     0
488     1
489     1
490     1
491     1
492     0
493     1
494     1
495     1
496     1
497     1
498     1
499     1
500     1
501     1
502     1
503     1
504     1
505     0
506     1
507     1
508     1
509     1
510     1
511     1
512     1
513     1
514     1
515     0
516     1
517     0
518     0
519     1
520     1
521     1
522     1
523     1
524     1
525     0
526     1
527     0
528     1
529     0
530     1
531     0
532     1
533     1
534     1
535     1
536     1
537     1
538     1
539     1
540     1
541     0
542     1
543     1
544     1
545     1
546     1
547     1
548     1
549     1
550     1
551     1
552     1
553     1
554     1
555     1
556     1
557     1
558     1
559     1
560     1
561     1
562     1
563     1
564     0
565     1
566     1
567     1
568     1
569     1
570     1
571     1
572     1
573     1
574     1
575     1
576     0
577     1
578     1
579     0
580     1
581     1
582     1
583     0
584     1
585     1
586     1
587     1
588     1
589     1
590     1
591     0
592     0
593     0
594     1
595     1
596     1
597     1
598     0
599     1
600     1
601     1
602     1
603     1
604     1
605     1
606     1
607     0
608     1
609     1
610     1
611     0
612     1
613     1
614     1
615     1
616     1
617     1
618     1
619     1
620     1
621     1
622     1
623     1
624     1
625     1
626     1
627     1
628     1
629     0
630     0
631     1
632     1
633     1
634     1
635     0
636     1
637     1
638     1
639     1
640     1
641     1
642     1
643     1
644     1
645     1
646     1
647     1
648     0
649     1
650     0
651     1
652     1
653     1
654     1
655     1
656     1
657     1
658     1
659     1
660     0
661     1
662     1
663     1
664     1
665     1
666     1
667     1
668     1
669     1
670     1
671     1
672     0
673     0
674     1
675     1
676     1
677     1
678     1
679     1
680     1
681     1
682     1
683     1
684     0
685     1
686     1
687     1
688     1
689     1
690     0
691     1
692     1
693     1
694     1
695     1
696     1
697     1
698     1
699     1
700     1
701     1
702     1
703     1
704     1
705     1
706     1
707     1
708     1
709     0
710     0
711     1
712     1
713     0
714     1
715     1
716     1
717     0
718     1
719     0
720     1
721     1
722     1
723     1
724     1
725     1
726     1
727     1
728     1
729     1
730     1
731     0
732     1
733     1
734     1
735     1
736     1
737     1
738     0
739     1
740     1
741     1
742     1
743     1
744     1
745     1
746     1
747     1
748     0
749     1
750     1
751     0
752     0
753     1
754     1
755     1
756     1
757     1
758     1
759     1
760     1
761     0
762     1
763     0
764     1
765     1
766     0
767     1
768     1
769     1
770     1
771     1
772     1
773     1
774     1
775     1
776     1
777     1
778     1
779     1
780     1
781     1
782     1
783     1
784     0
785     1
786     1
787     1
788     0
789     0
790     1
791     1
792     1
793     1
794     1
795     1
796     1
797     0
798     1
799     1
800     1
801     0
802     1
803     0
804     0
805     1
806     1
807     1
808     1
809     1
810     1
811     1
812     1
813     0
814     1
815     0
816     1
817     1
818     1
819     1
820     1
821     1
822     1
823     0
824     0
825     1
826     1
827     1
828     1
829     1
830     1
831     0
832     1
833     0
834     1
835     1
836     1
837     0
838     1
839     0
840     0
841     1
842     1
843     1
844     0
845     1
846     1
847     1
848     1
849     1
850     0
851     1
852     1
853     1
854     1
855     1
856     0
857     1
858     1
859     1
860     1
861     1
862     1
863     1
864     1
865     1
866     0
867     1
868     0
869     0
870     0
871     1
872     1
873     1
874     1
875     1
876     0
877     1
878     0
879     0
880     0
881     0
882     1
883     1
884     1
885     1
886     1
887     1
888     1
889     1
890     1
891     1
892     1
893     1
894     1
895     1
896     1
897     1
898     1
899     1
900     0
901     1
902     1
903     1
904     1
905     1
906     1
907     0
908     1
909     1
910     0
911     1
912     1
913     1
914     1
915     1
916     1
917     1
918     1
919     1
920     1
921     1
922     1
923     1
924     1
925     1
926     1
927     1
928     1
929     1
930     0
931     1
932     1
933     1
934     1
935     0
936     1
937     1
938     1
939     0
940     1
941     1
942     1
943     0
944     1
945     1
946     1
947     0
948     1
949     1
950     1
951     1
952     1
953     1
954     1
955     0
956     1
957     1
958     1
959     1
960     1
961     1
962     0
963     1
964     1
965     1
966     1
967     1
968     1
969     1
970     1
971     1
972     1
973     1
974     1
975     1
976     1
977     1
978     1
979     1
980     1
981     1
982     1
983     0
984     1
985     1
986     1
987     1
988     1
989     1
990     1
991     1
992     1
993     1
994     1
995     1
996     1
997     1
998     1
999     1
1000    1
1001    1
1002    0
1003    1
1004    1
1005    1
1006    1
1007    0
1008    1
1009    1
1010    1
1011    1
1012    1
1013    1
1014    1
1015    1
1016    1
1017    0
1018    1
1019    1
1020    1
1021    1
1022    0
1023    1
1024    1
1025    1
1026    1
1027    1
1028    1
1029    1
1030    1
1031    1
1032    1
1033    1
1034    1
1035    1
1036    1
1037    1
1038    1
1039    1
1040    1
1041    1
1042    1
1043    1
1044    1
1045    0
1046    1
1047    1
1048    0
1049    1
1050    0
1051    1
1052    1
1053    1
1054    1
1055    1
1056    1
1057    1
1058    1
1059    1
1060    0
1061    1
1062    1
1063    1
1064    0
1065    1
1066    1
1067    1
1068    1
1069    0
1070    1
1071    1
1072    0
1073    0
1074    1
1075    1
1076    1
1077    1
1078    1
1079    1
1080    1
1081    1
1082    1
1083    1
1084    1
1085    1
1086    1
1087    1
1088    1
1089    0
1090    1
1091    0
1092    1
1093    1
1094    1
1095    1
1096    1
1097    0
1098    1
1099    1
1100    1
1101    1
1102    1
1103    1
1104    1
1105    0
1106    1
1107    1
1108    1
1109    1
1110    1
1111    1
1112    1
1113    1
1114    1
1115    1
1116    1
1117    1
1118    0
1119    1
1120    0
1121    1
1122    0
1123    1
1124    1
1125    1
1126    0
1127    1
1128    1
1129    0
1130    1
1131    1
1132    1
1133    1
1134    1
1135    1
1136    1
1137    0
1138    1
1139    1
1140    1
1141    1
1142    0
1143    1
1144    1
1145    1
1146    0
1147    1
1148    1
1149    1
1150    1
1151    1
1152    1
1153    1
1154    0
1155    1
1156    1
1157    1
1158    1
1159    1
1160    1
1161    1
1162    1
1163    0
1164    1
1165    1
1166    1
1167    1
1168    1
1169    1
1170    1
1171    1
1172    0
1173    1
1174    1
1175    1
1176    1
1177    1
1178    1
1179    1
1180    1
1181    1
1182    1
1183    1
1184    1
1185    1
1186    1
1187    1
1188    1
1189    1
1190    1
1191    1
1192    1
1193    1
1194    0
1195    1
1196    0
1197    1
1198    1
1199    1
1200    1
1201    1
1202    1
1203    1
1204    1
1205    0
1206    1
1207    0
1208    1
1209    1
1210    1
1211    1
1212    1
1213    1
1214    1
1215    1
1216    1
1217    0
1218    1
1219    1
1220    1
1221    0
1222    1
1223    1
1224    1
1225    0
1226    1
1227    0
1228    1
1229    0
1230    1
1231    1
1232    1
1233    1
1234    1
1235    1
1236    1
1237    1
1238    1
1239    1
1240    1
1241    1
1242    1
1243    1
1244    1
1245    1
1246    1
1247    1
1248    1
1249    1
1250    1
1251    1
1252    0
1253    1
1254    1
1255    1
1256    1
1257    1
1258    1
1259    1
1260    1
1261    1
1262    1
1263    0
1264    1
1265    1
1266    1
1267    1
1268    1
1269    0
1270    1
1271    1
1272    1
1273    1
1274    0
1275    1
1276    1
1277    1
1278    1
1279    1
1280    1
1281    1
1282    1
1283    1
1284    1
1285    1
1286    1
1287    1
1288    1
1289    1
1290    1
1291    1
1292    1
1293    1
1294    1
1295    1
1296    1
1297    1
1298    1
1299    1
1300    1
1301    1
1302    1
1303    1
1304    1
1305    1
1306    1
1307    0
1308    0
1309    1
1310    1
1311    1
1312    1
1313    1
1314    1
1315    1
1316    1
1317    1
1318    0
1319    1
1320    1
1321    1
1322    1
1323    1
1324    1
1325    1
1326    1
1327    1
1328    0
1329    1
1330    1
1331    1
1332    1
1333    1
1334    1
1335    1
1336    1
1337    1
1338    1
1339    1
1340    1
1341    1
1342    1
1343    1
1344    1
1345    1
1346    1
1347    1
1348    1
1349    1
1350    0
1351    1
1352    1
1353    1
1354    1
1355    1
1356    1
1357    1
1358    1
1359    1
1360    1
1361    1
1362    1
1363    1
1364    1
1365    1
1366    0
1367    1
1368    1
1369    1
1370    1
1371    1
1372    1
1373    1
1374    0
1375    0
1376    1
1377    1
1378    0
1379    1
1380    0
1381    1
1382    1
1383    1
1384    1
1385    1
1386    1
1387    1
1388    1
1389    1
1390    1
1391    1
1392    1
1393    1
1394    1
1395    1
1396    1
1397    1
1398    1
1399    1
1400    1
1401    1
1402    1
1403    1
1404    1
1405    1
1406    1
1407    0
1408    1
1409    1
1410    1
1411    1
1412    1
1413    1
1414    0
1415    1
1416    1
1417    1
1418    1
1419    1
1420    1
1421    1
1422    1
1423    0
1424    1
1425    1
1426    1
1427    1
1428    1
1429    1
1430    0
1431    1
1432    1
1433    1
1434    1
1435    1
1436    1
1437    1
1438    1
1439    1
1440    1
1441    1
1442    1
1443    1
1444    0
1445    1
1446    1
1447    1
1448    1
1449    0
1450    1
1451    1
1452    1
1453    1
1454    1
1455    1
1456    0
1457    1
1458    0
1459    1
1460    0
1461    1
1462    1
1463    0
1464    1
1465    1
1466    0
1467    1
1468    1
1469    0
1470    1
1471    1
1472    1
1473    1
1474    1
1475    1
1476    1
1477    1
1478    1
1479    1
1480    1
1481    1
1482    1
1483    1
1484    1
1485    1
1486    1
1487    1
1488    1
1489    1
1490    1
1491    1
1492    0
1493    1
1494    1
1495    1
1496    1
1497    1
1498    1
1499    1
1500    0
1501    1
1502    0
1503    1
1504    1
1505    1
1506    1
1507    0
1508    1
1509    1
1510    1
1511    1
1512    1
1513    1
1514    1
1515    1
1516    1
1517    1
1518    0
1519    1
1520    1
1521    0
1522    1
1523    1
1524    1
1525    1
1526    1
1527    1
1528    1
1529    1
1530    1
1531    1
1532    1
1533    1
1534    1
1535    1
1536    0
1537    1
1538    1
1539    1
1540    1
1541    1
1542    1
1543    1
1544    0
1545    1
1546    1
1547    1
1548    1
1549    1
1550    1
1551    1
1552    1
1553    1
1554    1
1555    1
1556    1
1557    1
1558    1
1559    1
1560    1
1561    1
1562    1
1563    1
1564    1
1565    1
1566    1
1567    1
1568    1
1569    1
1570    1
1571    1
1572    1
1573    0
1574    0
1575    1
1576    1
1577    1
1578    1
1579    1
1580    1
1581    1
1582    1
1583    1
1584    1
1585    1
1586    1
1587    1
1588    1
1589    1
1590    1
1591    1
1592    1
1593    1
1594    0
1595    1
1596    1
1597    0
1598    0
1599    1
1600    1
1601    1
1602    1
1603    1
1604    1
1605    1
1606    1
1607    1
1608    1
1609    1
1610    1
1611    1
1612    1
1613    0
1614    1
1615    1
1616    1
1617    1
1618    1
1619    1
1620    1
1621    1
1622    1
1623    0
1624    1
1625    0
1626    1
1627    1
1628    0
1629    1
1630    1
1631    1
1632    1
1633    1
1634    1
1635    0
1636    1
1637    1
1638    0
1639    1
1640    0
1641    1
1642    1
1643    1
1644    1
1645    1
1646    1
1647    1
1648    1
1649    1
1650    1
1651    1
1652    1
1653    0
1654    1
1655    1
1656    1
1657    1
1658    1
1659    0
1660    1
1661    1
1662    1
1663    0
1664    1
1665    1
1666    1
1667    1
1668    1
1669    1
1670    1
1671    1
1672    1
1673    0
1674    0
1675    1
1676    1
1677    1
1678    1
1679    1
1680    1
1681    1
1682    1
1683    1
1684    1
1685    1
1686    1
1687    0
1688    0
1689    1
1690    1
1691    0
1692    1
1693    1
1694    1
1695    1
1696    1
1697    1
1698    1
1699    0
1700    1
1701    1
1702    1
1703    1
1704    1
1705    1
1706    1
1707    1
1708    1
1709    1
1710    1
1711    1
1712    1
1713    1
1714    0
1715    1
1716    1
1717    1
1718    0
1719    1
1720    1
1721    1
1722    1
1723    1
1724    1
1725    1
1726    1
1727    1
1728    1
1729    1
1730    1
1731    1
1732    1
1733    1
1734    0
1735    1
1736    1
1737    1
1738    1
1739    1
1740    1
1741    0
1742    1
1743    1
1744    1
1745    0
1746    1
1747    1
1748    1
1749    1
1750    1
1751    1
1752    1
1753    1
1754    1
1755    1
1756    1
1757    1
1758    1
1759    1
1760    1
1761    1
1762    1
1763    1
1764    1
1765    0
1766    1
1767    0
1768    1
1769    1
1770    1
1771    1
1772    1
1773    1
1774    1
1775    1
1776    1
1777    0
1778    0
1779    1
1780    0
1781    0
1782    1
1783    1
1784    1
1785    1
1786    1
1787    1
1788    1
1789    1
1790    1
1791    1
1792    1
1793    0
1794    1
1795    1
1796    1
1797    1
1798    1
1799    1
1800    1
1801    1
1802    1
1803    1
1804    1
1805    1
1806    1
1807    0
1808    1
1809    1
1810    1
1811    1
1812    1
1813    1
1814    1
1815    1
1816    1
1817    1
1818    1
1819    1
1820    1
1821    1
1822    1
1823    1
1824    1
1825    1
1826    1
1827    1
1828    1
1829    1
1830    0
1831    1
1832    1
1833    1
1834    1
1835    1
1836    1
1837    1
1838    1
1839    0
1840    1
1841    1
1842    1
1843    1
1844    1
1845    1
1846    1
1847    1
1848    0
1849    1
1850    1
1851    1
1852    1
1853    0
1854    1
1855    1
1856    1
1857    1
1858    1
1859    1
1860    1
1861    1
1862    1
1863    1
1864    1
1865    1
1866    1
1867    1
1868    1
1869    1
1870    1
1871    1
1872    1
1873    1
1874    0
1875    0
1876    0
1877    1
1878    1
1879    1
1880    0
1881    1
1882    1
1883    1
1884    1
1885    1
1886    1
1887    0
1888    0
1889    1
1890    1
1891    1
1892    1
1893    0
1894    1
1895    0
1896    1
1897    1
1898    1
1899    1
1900    1
1901    1
1902    1
1903    1
1904    0
1905    1
1906    1
1907    1
1908    1
1909    1
1910    1
1911    1
1912    1
1913    1
1914    1
1915    0
1916    1
1917    1
1918    1
1919    1
1920    1
1921    1
1922    1
1923    1
1924    1
1925    1
1926    1
1927    1
1928    1
1929    0
1930    0
1931    1
1932    1
1933    1
1934    1
1935    1
1936    1
1937    1
1938    1
1939    1
1940    0
1941    1
1942    0
1943    1
1944    1
1945    1
1946    1
1947    1
1948    1
1949    1
1950    1
1951    1
1952    1
1953    1
1954    1
1955    1
1956    1
1957    1
1958    1
1959    1
1960    1
1961    0
1962    1
1963    0
1964    1
1965    1
1966    1
1967    1
1968    1
1969    1
1970    0
1971    1
1972    1
1973    1
1974    1
1975    1
1976    1
1977    1
1978    0
1979    1
1980    1
1981    1
1982    1
1983    1
1984    1
1985    0
1986    1
1987    1
1988    1
1989    1
1990    1
1991    1
1992    1
1993    0
1994    1
1995    1
1996    1
1997    1
1998    1
1999    1

In [10]:
#split data in train and test data
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size = 0.2 ,  random_state = 3)

In [11]:
print(X.shape)
print(X_train.shape)
print(X_test.shape)

(5572,)
(4457,)
(1115,)

In [12]:
#feature extraction
#convert text into feature vectors 
feature_extraction = TfidfVectorizer(min_df =1 , stop_words = 'english', lowercase = True )
X_train_feature = feature_extraction.fit_transform(X_train)
X_test_feature = feature_extraction.transform(X_test)

#convert y test and y train into integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

In [13]:
print(X_train_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504033
  (1, 3046)	0.2503712792613518
  (1, 1991)	0.33036995955537024
  (1, 2956)	0.33036995955537024
  (1, 2758)	0.3226407885943799
  (1, 1839)	0.2784903590561455
  (1, 918)	0.22871581159877646
  (1, 2746)	0.3398297002864083
  (1, 2957)	0.3398297002864083
  (1, 3325)	0.31610586766078863
  (1, 3185)	0.29694482957694585
  (1, 4080)	0.18880584110891163
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.41872147309323743
  (4, 487)	0.2899118421746198
  :	:
  (4454, 2855)	0.47210665083641806
  (4454, 2246)	0.47210665083641806
  (4455, 4456)	0.24920025316220423
  (4455, 3922)	0.31287563163368587
  (4455, 6916)	0.19636985317119715
  (4455, 4715)	0.30714144758811196
  (4455, 3872)	0.3108911491788658
  (4455, 7113)	0.30536590342067704
  (4455, 6091)	0.23103841516927642
  (4455, 6810)	0.29731757715898277
  (4455, 5646)	0.33545678464631296
  (4455, 2469)	0.35441545511837946
  (4455, 2247)	0.37052851863170466
  (4456, 2870)	0.31523196273113385
  (4456, 5778)	0.16243064490100795
  (4456, 334)	0.2220077711654938
  (4456, 6307)	0.2752760476857975
  (4456, 6249)	0.17573831794959716
  (4456, 7150)	0.3677554681447669
  (4456, 7154)	0.24083218452280053
  (4456, 6028)	0.21034888000987115
  (4456, 5569)	0.4619395404299172
  (4456, 6311)	0.30133182431707617
  (4456, 647)	0.30133182431707617
  (4456, 141)	0.292943737785358

In [14]:
#training model
#X_train_feature LogisticRegression
model = LogisticRegression()

In [15]:
model.fit(X_train_feature , Y_train)

LogisticRegression()

In [16]:
#prediction on train data

prediction_on_training_data = model.predict(X_train_feature)
accuracy_on_training_data = accuracy_score(Y_train , prediction_on_training_data)

In [17]:
print(accuracy_on_training_data)

0.9676912721561588

In [18]:
#prediction on test data

prediction_on_testing_data = model.predict(X_test_feature)
accuracy_on_testing_data = accuracy_score(Y_test , prediction_on_testing_data)

In [19]:
print(accuracy_on_testing_data)

0.9668161434977578

In [20]:
#predictive model

input_mail = ["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"]
#convert text to feature vectors
input_data_feature = feature_extraction.transform(input_mail)
#making prediction

prediction = model.predict(input_data_feature)
print(prediction)

if prediction[0]==1:
    print('non spam mail')
else:
    print('spam mail')

[0]
spam mail

In [23]:
import joblib

# IMPORTANT: Replace 'my_trained_model' and 'my_vectorizer' 
# with the actual variable names you used in your code.

# 1. Save the trained model
joblib.dump(model, 'spam_model.pkl')

# 2. Save the text vectorizer (CountVectorizer or TfidfVectorizer)
joblib.dump(feature_extraction, 'vectorizer.pkl')

print("Success! Model and Vectorizer have been saved as .pkl files.")

Success! Model and Vectorizer have been saved as .pkl files.